const ATS_KEYWORDS = [
  "python", "java", "sql", "spring", "react", "aws", "docker", "kubernetes",
  "api", "rest", "machine learning", "ai", "rag", "llm", "agile", "git",
  "typescript", "node", "fastapi", "postgresql", "microservices", "ci/cd"
];

function extractKeywords(text) {
  const lower = text.toLowerCase();
  const found = ATS_KEYWORDS.filter((k) => lower.includes(k));
  const missing = ATS_KEYWORDS.filter((k) => !lower.includes(k));
  return { found, missing };
}

function parseResumeSections(text) {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const sections = { summary: [], experience: [], skills: [], education: [] };
  let current = "summary";
  for (const line of lines) {
    const h = line.toLowerCase();
    if (/^(experience|work history)/.test(h)) current = "experience";
    else if (/^skills/.test(h)) current = "skills";
    else if (/^education/.test(h)) current = "education";
    else if (/^summary|profile|objective/.test(h)) current = "summary";
    else sections[current].push(line);
  }
  return sections;
}

export function analyzeResume(text) {
  if (!text?.trim()) {
    return { success: false, message: "Resume text is required" };
  }

  const lower = text.toLowerCase();
  const { found, missing } = extractKeywords(text);
  const sections = parseResumeSections(text);
  const lineCount = text.split("\n").filter((l) => l.trim()).length;
  const hasMetrics = /\d+%|\d+ (users|ms|seconds|requests|improvements|million)/i.test(text);
  const hasProjects = /project/i.test(lower);

  let score = Math.round((found.length / ATS_KEYWORDS.length) * 55);
  score += Math.min(15, Math.floor(text.length / 400));
  if (hasMetrics) score += 12;
  if (hasProjects) score += 8;
  if (sections.skills.length >= 3) score += 5;
  if (lineCount >= 12) score += 5;
  score = Math.min(100, score);

  const keywordSuggestions = missing.slice(0, 6).map((k) => `Add "${k}" where relevant in skills or experience bullets`);
  const recommendations = [];
  if (score < 60) recommendations.push("Restructure experience with quantified outcomes (e.g., reduced latency 40%).");
  if (missing.length > 4) recommendations.push("Integrate missing keywords naturally in a dedicated Skills section.");
  if (!hasProjects) recommendations.push("Add 1–2 portfolio projects with tech stack and impact metrics.");
  if (lineCount < 12) recommendations.push("Expand content — ATS prefers detailed role descriptions.");
  recommendations.push("Use standard section headers: Summary, Experience, Skills, Education.");

  return {
    success: true,
    atsScore: score,
    matchingScore: score,
    foundKeywords: found,
    missingKeywords: missing.slice(0, 10),
    keywordSuggestions,
    recommendations,
    suggestion: score >= 75 ? "Strong ATS match. Polish with metrics and project links." : "Improve keyword coverage and quantify achievements.",
    sections
  };
}

export function tailorResume(resume, jobDescription) {
  if (!resume?.trim() || !jobDescription?.trim()) {
    return { success: false, message: "Resume and job description are required" };
  }

  const jdLower = jobDescription.toLowerCase();
  const resumeLower = resume.toLowerCase();
  const { found: resumeKw } = extractKeywords(resume);
  const { found: jdKw, missing: jdMissing } = extractKeywords(jobDescription);

  const matched = ATS_KEYWORDS.filter((k) => jdLower.includes(k) && resumeLower.includes(k));
  const missingSkills = ATS_KEYWORDS.filter((k) => jdLower.includes(k) && !resumeLower.includes(k)).slice(0, 8);
  const matchingScore = jdKw.length
    ? Math.min(100, Math.round((matched.length / Math.max(jdKw.length, 1)) * 100))
    : Math.round((matched.length / ATS_KEYWORDS.length) * 100);

  const roleLine = jobDescription.split("\n").find((l) => l.trim().length > 10) || "Target Role";
  const summary = `Results-driven engineer aligned with ${roleLine.trim().slice(0, 80)} — emphasizing ${matched.slice(0, 5).join(", ") || "core stack skills"}.`;

  const tailored = `${resume.split("\n")[0] || "Your Name"}

PROFESSIONAL SUMMARY
${summary}

TAILORED FOR THIS ROLE
${jobDescription.split("\n").slice(0, 3).join("\n")}

KEY ALIGNMENT
${matched.map((k) => `• Demonstrated ${k} experience matching job requirements`).join("\n") || "• Highlight relevant project outcomes"}

RECOMMENDED ADDITIONS
${missingSkills.map((k) => `• Weave "${k}" into experience bullets where truthful`).join("\n") || "• Resume already covers primary keywords"}

EXPERIENCE (optimized phrasing)
${resume.split("\n").slice(1).join("\n").trim() || resume}

---
Generated by NexusAI Tailor Resume — review and edit before submitting.`;

  const suggestedImprovements = [
    ...missingSkills.slice(0, 4).map((s) => `Highlight ${s} in your summary and skills section`),
    matchingScore < 70 ? "Add quantified outcomes that mirror job requirements" : "Strong alignment — tighten summary for this role"
  ];

  return {
    success: true,
    matchingScore,
    missingSkills,
    suggestedImprovements,
    tailoredResume: tailored,
    matchedKeywords: matched
  };
}
